export const GET_TASKS_LOAD = "GET_TASKS_LOAD";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAIL = "GET_TASKS_FAIL";

export const DONE_TASKS_LOAD = "DONE_TASKS_LOAD";
export const DONE_TASKS_SUCCESS = "DONE_TASKS_SUCCESS";
export const DONE_TASKS_FAIL = "DONE_TASKS_FAIL";

export const GET_TASK_BYID_LOAD = "GET_TASK_BYID_LOAD";
export const GET_TASK_BYID_SUCCESS = "GET_TASK_BYID_SUCCESS";
export const GET_TASK_BYID_FAIL = "GET_TASK_BYID_FAIL";

export const DELETE_TASK_BYID_LOAD = "DELETE_TASK_BYID_LOAD";
export const DELETE_TASK_BYID_SUCCESS = "DELETE_TASK_BYID_SUCCESS";
export const DELETE_TASK_BYID_FAIL = "DELETE_TASK_BYID_FAIL";

export const ADD_TASK_LOAD = "ADD_TASK_LOAD";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const EDIT_TASK_LOAD = "EDIT_TASK_LOAD";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";